# Generated by Django 3.0.8 on 2020-07-21 16:58

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=stdimage.models.JPEGField(upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget', models.CharField(max_length=10)),
                ('widget_id', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.Group')),
            ],
        ),
    ]
