# Generated by Django 3.0.8 on 2020-07-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('widgets', '0002_auto_20200721_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_1', models.TextField()),
                ('content_2', models.TextField()),
                ('behavioral_model', models.CharField(choices=[('url', 'Url'), ('resource', 'Resource'), ('content', 'Content')], default='url', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
